services:
  restx-frontend:
    image: hunghuynh5724/restx-frontend:latest
    container_name: restx-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

